version: '3.8'

services:
  gitlab:
    build:
      context: .
    container_name: gitlab
    restart: always
    hostname: gitlab.example.com
    ports:
      - "80:80"
      - "443:443"
      - "22:22"
    volumes:
      - gitlab-config:/etc/gitlab
      - gitlab-data:/var/opt/gitlab
      - gitlab-logs:/var/log/gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.example.com'
        gitlab_rails['gitlab_shell_ssh_port'] = 22
        gitlab_rails['smtp_enable'] = false
    networks:
      - gitlab-network

  db:
    image: postgres:13
    container_name: gitlab-db
    restart: always
    environment:
      POSTGRES_USER: gitlab
      POSTGRES_PASSWORD: gitlab_pass
      POSTGRES_DB: gitlab
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - gitlab-network

volumes:
  gitlab-config:
  gitlab-data:
  gitlab-logs:
  db-data:

networks:
  gitlab-network:
    driver: bridge
